#!/usr/bin/zsh

xrdb ~/.Xresources
getcolors() {
	FOREGROUND=#D9E0EE
	BACKGROUND=#302D41
	BLACK=#161320
	RED=#F28FAD
	GREEN=#ABE9B3
	YELLOW=#FAE3B0
	BLUE=#96CDFB
	MAGENTA=#DDB6F2
	CYAN=#B5E8E0
	WHITE=#D9E0EE
}
getcolors

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'terminal' 'browser' 'micro' 'chat' 'media' 'I' 'II' 'III'
		let name++
	done
}
workspaces

bspc config border_width 5
bspc config window_gap 28
bspc config split_ratio 0.50

# Fixes resizing bug
bspc config pointer_motion_interval 16.67

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Remove all rules
bspc rule -r *

# 5 - media
declare -a media=(mpv Zathura feh)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done
