#!/usr/bin/zsh

xrdb ~/.Xresources
getcolors() {
	FOREGROUND=#e0def4
	BACKGROUND=#191724
	BLACK=#161320
	RED=#eb6f92
	GREEN=#3e8fb0
	YELLOW=#f6c177
	BLUE=#9ccfd8
	MAGENTA=#c4a7e7
	CYAN=#9ccfd8
	WHITE=#e0def4
}
getcolors

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'terminal' 'browser' 'helix' 'chat' 'media' 'I' 'II' 'III' 'IV'
		let name++
	done
}
workspaces

bspc config border_width 0
bspc config window_gap 32
bspc config split_ratio 0.50

# Fixes resizing bug
bspc config pointer_motion_interval 16

bspc config focused_border_color "$CYAN" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Remove all rules
bspc rule -r *

# 2 - Brave
bspc rule -a Brave-browser desktop='^2'

# 4 - Discord Canary
bspc rule -a DiscordCanary desktop='^2'

# 5 - media
declare -a media=(mpv Zathura feh)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done
